### ISSUE TITLE
Test: Cannot find module 'grpc' from 'grpc_connection.js'

### ISSUE THREAD

**Issue by glebec** [guilherme6191/react-router-firebase-auth-material-ui#1]
```
npm t
```

```sh
 FAIL  src/App.test.js
  ● Test suite failed to run

    Cannot find module 'grpc' from 'grpc_connection.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (node_modules/@firebase/firestore/dist/cjs/src/platform_node/grpc_connection.js:29:12)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.045s
Ran all test suites.
```

**Comment by glebec** [comment]
Answer appears to be:

In package.json, add `--browser` to the `test` script.

In `App.test.js`, add the `MuiThemeProvider`:

```
it('renders without crashing', () => {
    const div = document.createElement('div')
    ReactDOM.render(
        <MuiThemeProvider>
            <App />
        </MuiThemeProvider>,
        div,
    )
})
```

**Comment by guilherme6191** [comment]
Hey @glebec sorry for the delayed reply.

Thanks for contributing, do wanna open a PR? If not it's ok, I can do the fix.

Cheers

**Comment by glebec** [comment]
Sure, I'll whip up a PR — at the time I left this issue, I was in the middle of reviewing someone else's code, so it fell off my map.

There's another consideration, however, which is that perhaps you should use [Enzyme](https://github.com/airbnb/enzyme) to shallow-render your components, bypassing this issue altogether. What do you think? I can make that a separate issue and submit a small PR fix for the project as it currently stands, in the meantime.

**Comment by guilherme6191** [comment]
The basic setup was fully based on Create React App. So maybe devs could go to [CRA docs](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#testing-components) to change a bit the setup?

**Comment by glebec** [comment]
Sounds reasonable to me. 👍

**Comment by guilherme6191** [comment]
Awesome, thanks for contributing @glebec

**Comment by hhimanshu** [comment]
Hello there, 

I did the following 

```
"test": "node scripts/test.js --browser --env=jsdom"
```
But no luck, I still get  

```
  ● Test suite failed to run

    Cannot find module 'grpc' from 'grpc_connection.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (node_modules/@firebase/firestore/dist/cjs/src/platform_node/grpc_connection.js:29:12)
```  

I am using it via `create-react-app` and the relevant versions are  
```
"jest": "20.0.4",
    "react": "^15.6.1",
    "react-dev-utils": "^3.0.2",
    "react-dom": "^15.6.1",
    "react-error-overlay": "^1.0.9",
    "react-flexbox-grid": "^1.1.3",
    "react-ga": "^2.4.1",
    "react-redux": "^5.0.6",
    "react-responsive": "^4.1.0",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1",
    "react-router-hash-link": "^1.2.0",
```

What did I do wrong?
